### ISSUE TITLE
Concrete projection of flowpipes (cont)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/ReachabilityAnalysis.jl#158]
follow-up https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/145

---

we should also address [this comment](https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/291#issue-451204091)

**Comment by schillic** [comment]
https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/b580cff8ac8046581c368e604acd4e923160f4d5/src/Algorithms/GLGM06/project.jl#L43

Not sure if this is still used. But instead of `linear_map`, the function `project` from `LazySets` should be used directly (see https://github.com/JuliaReach/LazySets.jl/issues/2147).

**Comment by mforets** [comment]
those are indeed some leftovers from the previous codebase and can be removed (https://github.com/JuliaReach/ReachabilityAnalysis.jl/pull/163).
