### ISSUE TITLE
Changing solver 

### ISSUE THREAD

**Issue by ga72kud** [JuliaReach/ReachabilityAnalysis.jl#596]
I want to change the solver GLGM06 to another solver. I am currently struggling with changing it to another solver.

```julia
using LazySets, SparseArrays
using Plots, LinearAlgebra
using ExponentialUtilities, ReachabilityAnalysis
A = [0 0 1.0 0;0 0 0 1.0;0 0 0 0; 0 0 0 0]
B = [1.0 0; 0 1.0; 0 0; 0 0]
δ = 0.1;
μ = 1.05
T = 2.
P = [1.0 0 0 0;0 1.0 0 0]

X0 = Ellipsoid(ones(4), Diagonal([2.0, 0.5, 3.8, .4]))
B = [0 0;0 0;1.0 0; 0 1.0]
U = Ball2(zeros(2), μ);
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, alg=GLGM06(δ=δ), T=T);
plot(sol, vars=(1, 2), lab="R", fillalpha=0.1, layout=(1,2))
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=1)

X0=Approximations.overapproximate(X0)
U=Approximations.overapproximate(U)
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, tspan=(0.0, T), alg=GLGM06(δ=δ))
plot!(sol, vars=(1, 2), lab="R", fillalpha=0.1, subplot=2)
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=2)
```

Similar to https://github.com/JuliaReach/ReachabilityAnalysis.jl/issues/595

I guess that the documentation will follow, but maybe you can help me to fix this problem with ORBIT and LGG09

**Comment by schillic** [comment]
Just replace the keyword argument `alg=GLGM06(δ=δ)` with the other solver. Some comments:

* For `ORBIT` your `X0` needs to be a singleton (contain just a single state).

https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/2d4298d05c52267fb6d7505d48dcddaf9019c05c/src/Algorithms/ORBIT/ORBIT.jl#L4-L5

Btw @mforets I think "deterministic" and "proper input set" do not go together. What it means is that the solver gives you an analytic simulation, which happens to be exact for deterministic systems. For systems with "proper input set" it gives you one of the possible analytic trajectories.

* `LGG09` is probably the only algorithm that works with your ellipsoid initial set (maybe even that fails, I did not test it)¹. That solver requires some additional parameters. It will throw appropriate error messages if you forget them. The most important parameter is that you need to specify directions in which you want to compute the bounds of the reachable states. For example, since you want to plot the result in dimensions 1 and 2, you can get interval bounds by passing `dirs=CustomDirections([[1.0, 0, 0, 0], [-1.0, 0, 0, 0], [0.0, 1, 0, 0], [0.0, -1, 0, 0]])`; for interval bounds you can alternatively use the convenience parameter `vars = [1, 2]` here, but if you want to obtain more bounds (e.g., diagonal bounds in those dimensions), you need to use `dirs` as above. You can study the code in the function starting below.

https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/2d4298d05c52267fb6d7505d48dcddaf9019c05c/src/Algorithms/LGG09/LGG09.jl#L60

¹You can use other solvers if you first overapproximate `X0` with another set representation (depending on the solver).

**Comment by ga72kud** [comment]
Thanks a lot, I tested ORBIT. As far as I understand it, it takes the initial state (programmed as singleton) and propagates iteratively over the system dynamics. It chooses a random input value specified the variable U (in my case a overapproximated control input, previously defined as Ball2). ORBIT only gives a random trajectory not really a reachable set (which is confusing for me in the documentation). Nevertheless thanks a lot.

```
using LazySets, SparseArrays
using Plots, LinearAlgebra
using ExponentialUtilities, ReachabilityAnalysis
A = [0 0 1.0 0;0 0 0 1.0;0 0 0 0; 0 0 0 0]
B = [1.0 0; 0 1.0; 0 0; 0 0]
δ = 0.1;
μ = 1.05
T = 2.
P = [1.0 0 0 0;0 1.0 0 0]

X0 = Ellipsoid(ones(4), Diagonal([2.0, 0.5, 3.8, .4]))
B = [0 0;0 0;1.0 0; 0 1.0]
U = Ball2(zeros(2), μ);
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, alg=GLGM06(δ=δ), T=T);
plot(sol, vars=(1, 2), lab="R", fillalpha=0.1, layout=(1,4))
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=1)

X0=Approximations.overapproximate(X0)
U=Approximations.overapproximate(U)
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, tspan=(0.0, T), alg=GLGM06(δ=δ))
plot!(sol, vars=(1, 2), lab="R", fillalpha=0.1, subplot=2)
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=2)

X0=LazySets.Singleton([2.0; 0.5; 3.8; .4])
U=Approximations.overapproximate(U)
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, tspan=(0.0, T), alg=GLGM06(δ=δ))
plot!(sol, vars=(1, 2), lab="R", fillalpha=0.1, subplot=2)
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=2)


X0=LazySets.Singleton([2.0; 0.5; 3.8; .4])
U=Approximations.overapproximate(U)
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, tspan=(0.0, T), alg=ORBIT(δ=δ))
plot!(sol, vars=(1, 2), lab="R", fillalpha=0.1, subplot=3)
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=3)
```

I try LGG09 with ellipsoid but I get an error. I guess I have to define a support function for the initial state sets...

**Comment by ga72kud** [comment]
with LGG09

I tested it like this. It computes the reach sets/flowpipes for different directions (support vectors). 

abc=BoxDirections(4)
abc=DiagDirections(4)
abc=OctDirections(4)
abc=CustomDirections([[3.4, 6.3, 1.0, 0.0], [-1.0, 2.4, 2.3, 0.0], [2.1, 1.0, 1.0, 1.2], [5.3, -1.0, 1.0, 0.0]]);
X0  = Zonotope(ones(4), Matrix(0.1*I, 4, 4))
U = Ball2(zeros(2), μ);
prob = @ivp(x' = A*x + B*u, x(0) ∈ X0, u ∈ U, x ∈ Universe(4))
sol = solve(prob, tspan=(0.0, T), alg=LGG09(δ=δ, template=abc))
plot!(sol, vars=(1, 2), lab="R", fillalpha=0.1, subplot=4)
plot!(P*X0, vars=(1, 2), lab="X0", fillalpha=0.1, subplot=4)

**Comment by schillic** [comment]
* For plotting a high-dimensional set (`X0` in the last line) you need to manually project (the `vars = (1, 2)` parameter only works for the solution sets from `ReachabilityAnalysis`:
```julia
plot!(project(X0, [1, 2]), lab="X0", fillalpha=0.1, subplot=4)
```
* I get warnings about an empty result with your `CustomDirections`, so they are probably not bounding in dimensions 1 and 2. This is tricky to get right, so maybe just use one of the other versions for `abc`. You can also create custom directions including the box directions (which guarantees boundedness). You can get the box directions via
```julia
collect(BoxDirections(4))
```

**Comment by ga72kud** [comment]
Thank you a lot !
