### ISSUE TITLE
Intersection of two reach sets

### ISSUE THREAD

**Issue by ga72kud** [JuliaReach/ReachabilityAnalysis.jl#598]
```julia
ℛₐ = ReachabilityAnalysis.solve(prob_set_sysₐ, alg=GLGM06(δ=Ts), T=TT[end], c=:yellow);
ℛᵦ = ReachabilityAnalysis.solve(prob_set_sysᵦ, alg=GLGM06(δ=Ts), T=TT[end], c=:yellow);
ℛ=ℛₐ∩ℛᵦ

```
Ra and Rb are from type RechabilityAnalysis.Reachsolution Is this possible to intersect both reach sets?

I tried something like this
```julia
        ℛ=[ℛₐ.F.Xk[i].X∩ℛᵦ.F.Xk[i].X for i in 1:length(ℛₐ.F.Xk)] #this does not work

        𝒫ℛₐ=project(ℛₐ , [1, 2])
        𝒫ℛᵦ=project(ℛᵦ , [1, 2])
        𝒫ℛ=𝒫ℛₐ∩𝒫ℛᵦ
        𝒫ℛ=[𝒫ℛₐ.Xk[i].X∩𝒫ℛᵦ.Xk[i].X for i in 1:length(𝒫ℛₐ.Xk)]
```

**Comment by schillic** [comment]
This seems to not be supported out of the box. But your workaround works for me, including

> `ℛ=[ℛₐ.F.Xk[i].X∩ℛᵦ.F.Xk[i].X for i in 1:length(ℛₐ.F.Xk)] #this does not work`

The problem is that you then lose all other information stored in the `ReachSet`s/`ReachSolution`. I agree that it would be nice to support this as an operation on the `ReachSolution` in the library.

There are other things to note here:
1. The operation `∩` is interpreted as a _lazy_ intersection (see [JuliaReach/LazySets.jl](https://github.com/JuliaReach/LazySets.jl) for details), which is you get a result quickly. If you want to instead compute the concrete intersection (expensive in general), you can do `ℛ = intersection.(ℛₐ, ℛᵦ)` (note the `.` for broadcasting). Interestingly, this is supported. But doing this is expensive in higher dimensions.
2. The reachable set used by `GLGM06` is represented by (a sequence of) zonotopes. For these an intersection can be computed (however, in general this can be expensive). For nonlinear systems we currently only support Taylor models and their intersection is not supported. But you can obtain conservative overapproximations.

**Comment by ga72kud** [comment]
Thanks! intersection. is what I can use, awesome!
